version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grx-app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "80:3000"
      - "5000:5000"
    volumes:
      - .:/home/node/app
      - grx-node_modules:/home/node/app/node_modules
    networks:
      - grx-network
    command: npm run dev

networks:
  grx-network:

volumes:
  grx-node_modules:    
